"""fix user, patient, episod tables

Revision ID: 60cc75192269
Revises: ea1d897cb8f1
Create Date: 2025-10-01 23:04:11.983936

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60cc75192269'
down_revision: Union[str, Sequence[str], None] = 'ea1d897cb8f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('episodes', 'pcr')
    op.add_column('patients', sa.Column('gender', sa.String(length=20), nullable=True))
    op.alter_column('patients', 'rut',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('patients', 'age',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('users', sa.Column('is_chief_doctor', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('is_doctor', sa.Boolean(), nullable=True))
    op.drop_column('users', 'role')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_column('users', 'is_doctor')
    op.drop_column('users', 'is_chief_doctor')
    op.alter_column('patients', 'age',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('patients', 'rut',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.drop_column('patients', 'gender')
    op.add_column('episodes', sa.Column('pcr', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
