"""Add insurance review table

Revision ID: 8791bf230a1c
Revises: e5ea0a93e116
Create Date: 2025-11-25 12:00:00.000000

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8791bf230a1c"
down_revision: Union[str, Sequence[str], None] = "e5ea0a93e116"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "insurance_reviews",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("episode_id", sa.Integer(), nullable=False),
        sa.Column("is_pertinent", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["episode_id"], ["episodes.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("episode_id"),
    )
    op.create_index(
        op.f("ix_insurance_reviews_id"), "insurance_reviews", ["id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_insurance_reviews_id"), table_name="insurance_reviews")
    op.drop_table("insurance_reviews")
    # ### end Alembic commands ###
