"""add auth role rut

Revision ID: c56eb3b2ba66
Revises: 1716e50a6773
Create Date: 2025-10-05 18:59:46.951452

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c56eb3b2ba66'
down_revision: Union[str, Sequence[str], None] = '1716e50a6773'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('rut', sa.String(length=20), nullable=False))
    op.add_column('users', sa.Column('hashed_password', sa.String(length=255), nullable=False))
    op.create_index(op.f('ix_users_rut'), 'users', ['rut'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_rut'), table_name='users')
    op.drop_column('users', 'hashed_password')
    op.drop_column('users', 'rut')
    # ### end Alembic commands ###
