"""create user, patient, episode, diagnostic tables and episode_diagnostic association table

Revision ID: ea1d897cb8f1
Revises: fbc1f0d2e1a2
Create Date: 2025-09-26 02:12:22.878997

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ea1d897cb8f1"
down_revision: Union[str, Sequence[str], None] = "fbc1f0d2e1a2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "diagnostics",
        sa.Column("cie_code", sa.String(length=20), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_diagnostics_cie_code"), "diagnostics", ["cie_code"], unique=True
    )
    op.create_index(op.f("ix_diagnostics_id"), "diagnostics", ["id"], unique=False)
    op.create_table(
        "patients",
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("rut", sa.String(length=20), nullable=False),
        sa.Column("age", sa.Integer(), nullable=False),
        sa.Column("active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_patients_id"), "patients", ["id"], unique=False)
    op.create_index(op.f("ix_patients_name"), "patients", ["name"], unique=False)
    op.create_index(op.f("ix_patients_rut"), "patients", ["rut"], unique=True)
    op.create_table(
        "users",
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("hashed_password", sa.String(length=255), nullable=False),
        sa.Column("role", sa.String(length=50), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(op.f("ix_users_id"), "users", ["id"], unique=False)
    op.create_table(
        "episodes",
        sa.Column("patient_id", sa.Integer(), nullable=False),
        sa.Column("numero_episodio", sa.String(length=50), nullable=False),
        sa.Column("fecha_ingreso", sa.Date(), nullable=True),
        sa.Column("fecha_estabilizacion", sa.Date(), nullable=True),
        sa.Column("fecha_alta", sa.Date(), nullable=True),
        sa.Column("validacion", sa.String(length=50), nullable=True),
        sa.Column("tipo", sa.String(length=50), nullable=True),
        sa.Column("tipo_alerta_ugcc", sa.String(length=100), nullable=True),
        sa.Column("mes_ingreso", sa.Integer(), nullable=True),
        sa.Column("fecha_egreso", sa.Date(), nullable=True),
        sa.Column("mes_egreso", sa.Integer(), nullable=True),
        sa.Column("centro", sa.String(length=100), nullable=True),
        sa.Column("antecedentes_cardiaco", sa.Boolean(), nullable=True),
        sa.Column("antecedentes_diabetes", sa.Boolean(), nullable=True),
        sa.Column("antecedentes_hipertension", sa.Boolean(), nullable=True),
        sa.Column("triage", sa.String(length=50), nullable=True),
        sa.Column("presion_sistolica", sa.Integer(), nullable=True),
        sa.Column("presion_diastolica", sa.Integer(), nullable=True),
        sa.Column("presion_media", sa.Integer(), nullable=True),
        sa.Column("temperatura_c", sa.Numeric(precision=4, scale=1), nullable=True),
        sa.Column("saturacion_o2", sa.Numeric(precision=4, scale=1), nullable=True),
        sa.Column("frecuencia_cardiaca", sa.Integer(), nullable=True),
        sa.Column("frecuencia_respiratoria", sa.Integer(), nullable=True),
        sa.Column("tipo_cama", sa.String(length=50), nullable=True),
        sa.Column("glasgow_score", sa.Integer(), nullable=True),
        sa.Column("fio2", sa.Numeric(precision=4, scale=1), nullable=True),
        sa.Column("fio2_ge_50", sa.Boolean(), nullable=True),
        sa.Column("ventilacion_mecanica", sa.Boolean(), nullable=True),
        sa.Column("cirugia_realizada", sa.Boolean(), nullable=True),
        sa.Column("cirugia_mismo_dia_ingreso", sa.Boolean(), nullable=True),
        sa.Column("hemodinamia", sa.Boolean(), nullable=True),
        sa.Column("hemodinamia_mismo_dia_ingreso", sa.Boolean(), nullable=True),
        sa.Column("endoscopia", sa.Boolean(), nullable=True),
        sa.Column("endoscopia_mismo_dia_ingreso", sa.Boolean(), nullable=True),
        sa.Column("dialisis", sa.Boolean(), nullable=True),
        sa.Column("trombolisis", sa.Boolean(), nullable=True),
        sa.Column("trombolisis_mismo_dia_ingreso", sa.Boolean(), nullable=True),
        sa.Column("pcr", sa.Boolean(), nullable=True),
        sa.Column("hemoglobina", sa.Numeric(precision=4, scale=1), nullable=True),
        sa.Column("creatinina", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("nitrogeno_ureico", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("sodio", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("potasio", sa.Numeric(precision=4, scale=2), nullable=True),
        sa.Column("dreo", sa.String(length=50), nullable=True),
        sa.Column("troponinas_alteradas", sa.Boolean(), nullable=True),
        sa.Column("ecg_alterado", sa.Boolean(), nullable=True),
        sa.Column("rnm_protocolo_stroke", sa.Boolean(), nullable=True),
        sa.Column("dva", sa.Boolean(), nullable=True),
        sa.Column("transfusiones", sa.Boolean(), nullable=True),
        sa.Column("compromiso_conciencia", sa.Boolean(), nullable=True),
        sa.Column("estado_del_caso", sa.String(length=50), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["patient_id"], ["patients.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_episodes_id"), "episodes", ["id"], unique=False)
    op.create_index(
        op.f("ix_episodes_numero_episodio"),
        "episodes",
        ["numero_episodio"],
        unique=True,
    )
    op.create_index(
        op.f("ix_episodes_patient_id"), "episodes", ["patient_id"], unique=False
    )
    op.create_table(
        "episode_diagnostic",
        sa.Column("episode_id", sa.Integer(), nullable=False),
        sa.Column("diagnostic_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["diagnostic_id"], ["diagnostics.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(["episode_id"], ["episodes.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("episode_id", "diagnostic_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("episode_diagnostic")
    op.drop_index(op.f("ix_episodes_patient_id"), table_name="episodes")
    op.drop_index(op.f("ix_episodes_numero_episodio"), table_name="episodes")
    op.drop_index(op.f("ix_episodes_id"), table_name="episodes")
    op.drop_table("episodes")
    op.drop_index(op.f("ix_users_id"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_patients_rut"), table_name="patients")
    op.drop_index(op.f("ix_patients_name"), table_name="patients")
    op.drop_index(op.f("ix_patients_id"), table_name="patients")
    op.drop_table("patients")
    op.drop_index(op.f("ix_diagnostics_id"), table_name="diagnostics")
    op.drop_index(op.f("ix_diagnostics_cie_code"), table_name="diagnostics")
    op.drop_table("diagnostics")
    # ### end Alembic commands ###
