"""init

Revision ID: fbc1f0d2e1a2
Revises:
Create Date: 2025-09-24 18:58:36.235971

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "fbc1f0d2e1a2"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
